// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"accident-service/internal/biz"
	"accident-service/internal/conf"
	"accident-service/internal/data"
	"accident-service/internal/route"
	"accident-service/internal/server"
	"accident-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	goCloak := data.NewKeycloak(confData)
	keycloakAPI := data.NewKeyCloakAPI(confData, goCloak, logger)
	dataData, cleanup, err := data.NewData(confData, logger, db, keycloakAPI)
	if err != nil {
		return nil, nil, err
	}
	accidentRepo := data.NewAccidentRepo(dataData, logger)
	accidentUseCase := biz.NewAccidentRepo(accidentRepo, logger)
	accidentService := service.NewAccidentService(accidentUseCase)
	grpcServer := server.NewGRPCServer(confServer, accidentService, logger)
	accidentRoute := route.NewAccidentRoute(accidentUseCase)
	httpServer := server.NewHTTPServer(confServer, accidentRoute, keycloakAPI, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
